import type { Metadata } from "next";
import { Inter, Noto_Serif_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

const noto = Noto_Serif_JP({
   subsets: ["latin"], 
   weight: ['400', '500', '600'],
   variable: '--font-noto'
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${noto.variable}`}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
